HTTP/1.0 502 Bad Gateway
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
<head><meta http-equiv="refresh" content="5"></head>
<body><center><h1>Error: 502 Bad Gateway.</h1>
The server could not connect to the application gateway.</center>
</body></html>
